### ISSUE TITLE
Questions for Koonjewarre

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#49]
There are a number of questions we need to ask the venue, I'm going to group them all here so I can call/email them through.

General
-------
- [ ] ~~What kind of internet connection/connection speed do you have? (aka is it reliable enough to do live captioning #11)~~ - it's not wired, probably not appropriate for captioning.
- [ ] What kind of fridge space is available (aka is there space for parents to store baby goods #48)
- [x] What does your insurance cover? (aka can folks byo alcohol? #47 )
- [ ] What kind of projector/amplification system do you have? (it's listed on the website, it might mean we can make #14 cheaper)
- [x] Is there a good space where we could set up childcare? Can we use The Cottage, or is there a way to partition The Farmhouse? (#25)
- [ ] We're looking to set up a time out zone in the empty room of the Dormitory Units. Is this still set up as a vacant space we can use for these purposes? (#50)
- [x] Do you have heaters? Do we need them? (#15)

Accessibility (#27)
-------------------
- [ ] What kind of accessibility info do you have?
- [ ] What's the gradient of the ramp from the main hall to the dining hall? Is it wheelchair accessible?
- [ ] Would you consider the farmhouse accessible by wheelchair?
- [ ] Are there accessible bathrooms/showers near the main hall?
- [ ] Is there accessible accommodation for folks in wheelchairs?
- [ ] Are service dogs welcome?

**Comment by SomeoneWeird** [comment]
The (local) networking setup at Koonjewarre was done by CampJS previously (maybe at IV?) - and the internet wasn't great. That being said might be worth asking if they have NBN now. Also worth checking if they have a bandwidth cap.

**Comment by AshKyd** [comment]
Good points @SomeoneWeird. I'm hoping we can set up the 4g system again in #46. For the purposes of live captioning in #11 we'll need a sturdy connection to send the audio feed, so hoping we can use the landline solely for that.

**Comment by AshKyd** [comment]
I've emailed through these questions.

**Comment by mcne65** [comment]
While it is a shame that there won't be any live captioning available for this, would you have a speakerphone and ask if people have a GitHub to put their slides up?
